"""add user_id

Revision ID: 9438c00bf6
Revises: 7e17e49d99
Create Date: 2015-03-06 00:30:44.857822

"""

# revision identifiers, used by Alembic.
revision = '9438c00bf6'
down_revision = '7e17e49d99'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'user_id')
    ### end Alembic commands ###
